### ISSUE TITLE
No Module Named Decompilers

### ISSUE THREAD

**Issue by gemclashing** [ptynecki/unfrozen_binary#1]
Hi, when I try to run, im getting this error: ModuleNotFoundError: No module named 'decompilers'
Anyway to fix?

**Comment by ptynecki** [comment]
Thanks for the issue.

You have right, `decompilers` directory (module) doesn't exists in current repository. I'm going to fix it this week, despite the fact that the project is deprecated.

**Comment by gemclashing** [comment]
Would appreciate if you do it ASAP, I waited 4 months for this :)

**Comment by ptynecki** [comment]
Could you pull current master version and check now?

https://github.com/ptynecki/unfrozen_binary/commit/27687459efda028582259b2544fdeb701ae50409

**Comment by gemclashing** [comment]
Trying now

**Comment by gemclashing** [comment]
`Traceback (most recent call last):
  File "unfrozen_binary_cx_Freeze.py", line 17, in <module>
    from common import uncompyle_decompilation
  File "C:\Users\2019l\Desktop\unfrozen_binary-master\common.py", line 18, in <module>
    from unpyc3.unpyc3 import dec_module
ModuleNotFoundError: No module named 'unpyc3.unpyc3'; 'unpyc3' is not a package` 

Getting that error

**Comment by gemclashing** [comment]
?
